name: CUDA CI on Windows

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
      
    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1.4.1
      
    - name: Install CUDA
      uses: nvidia/setup-cuda@v12
      
    - name: check CUDA version
      run: |
        nvcc -v
        
    - name: Build project
      run: |
        cd src && make

