name: Integration tests using calorine

on: [pull_request]

jobs:
  Integration_Test:
    runs-on: ubuntu-latest
    container: 
      image: nvidia/cuda:12.8.0-devel-ubuntu22.04
  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y build-essential
           
      - name: Install python dependencies
        run: python3 -m pip install calorine pytest

      - name: Build with Make, with DDEBUG
        run: cd src && make CFLAGS=-DDEBUG

      - name: Run integration test
        run: cd tests && pytest  # This requires a GPU runner
